# WITS Automation Configuration
credentials:
  email: "zask25802@gmail.com"
  password: "Abuji@2580"
  #query_name: ["Auto2010", "Auto2011", "Auto2012", "Auto2013"]

query_name: ["Auto2007", "Auto2008", "Auto2009", "Auto2010", "Auto2011", "Auto2012", "Auto2013", "Auto2014", "Auto2015", "Auto2016", "Auto2017", "Auto2018", "Auto2019", "Auto2020", "Auto2021", "Auto2022", "Auto2023", "Auto2024", "Auto2025"]
#query_name: ["Auto2007"]
urls:
  login: "https://wits.worldbank.org/WITS/WITS/Restricted/Login.aspx"

browser_settings:
  browser: "chromium"
  headless: true
  
workflow:
  execute_query: false
  download_query: true

iso3_to_country : {
    'ABW': 'Aruba',
    'AFG': 'Afghanistan',
    'AGO': 'Angola',
    'AIA': 'Anguila',
    'ALB': 'Albania',
    'ALI': 'Åland Islands',
    'AND': 'Andorra',
    'ANT': 'Netherlands Antilles',
    'ARE': 'United Arab Emirates',
    'ARG': 'Argentina',
    'ARM': 'Armenia',
    'ASM': 'American Samoa',
    'ATA': 'Antarctica',
    'ATF': 'Fr. So. Ant. Tr',
    'ATG': 'Antigua and Barbuda',
    'AUS': 'Australia',
    'AUT': 'Austria',
    'AZE': 'Azerbaijan',
    'BAT': 'Br. Antr. Terr',
    'BDI': 'Burundi',
    'BEL': 'Belgium',
    'BEN': 'Benin',
    'BES': 'Bonaire',
    'BFA': 'Burkina Faso',
    'BGD': 'Bangladesh',
    'BGR': 'Bulgaria',
    'BHR': 'Bahrain',
    'BHS': 'Bahamas, The',
    'BIH': 'Bosnia and Herzegovina',
    'BLM': 'Saint Barthélemy',
    'BLR': 'Belarus',
    'BLX': 'Belgium-Luxembourg',
    'BLZ': 'Belize',
    'BMU': 'Bermuda',
    'BOL': 'Bolivia',
    'BRA': 'Brazil',
    'BRB': 'Barbados',
    'BRN': 'Brunei',
    'BTN': 'Bhutan',
    'BUN': 'Bunkers',
    'BVT': 'Bouvet Island',
    'BWA': 'Botswana',
    'CAF': 'Central African Republic',
    'CAN': 'Canada',
    'CCK': 'Cocos (Keeling) Islands',
    'CHE': 'Switzerland',
    'CHL': 'Chile',
    'CHN': 'China',
    'CIV': "Cote d'Ivoire",
    'CMR': 'Cameroon',
    'COG': 'Congo, Rep.',
    'COK': 'Cook Islands',
    'COL': 'Colombia',
    'COM': 'Comoros',
    'CPV': 'Cape Verde',
    'CRI': 'Costa Rica',
    'CSK': 'Czechoslovakia',
    'CUB': 'Cuba',
    'CUW': 'Curaçao',
    'CXR': 'Christmas Island',
    'CYM': 'Cayman Islands',
    'CYP': 'Cyprus',
    'CZE': 'Czech Republic',
    'DDR': 'German Democratic Republic',
    'DEU': 'Germany',
    'DJI': 'Djibouti',
    'DMA': 'Dominica',
    'DNK': 'Denmark',
    'DOM': 'Dominican Republic',
    'DZA': 'Algeria',
    'ECU': 'Ecuador',
    'EGY': 'Egypt, Arab Rep.',
    'ERI': 'Eritrea',
    'ESH': 'Western Sahara',
    'ESP': 'Spain',
    'EST': 'Estonia',
    'ETF': 'Ethiopia(includes Eritrea)',
    'FIN': 'Finland',
    'FJI': 'Fiji',
    'FLK': 'Falkland Island',
    'FRA': 'France',
    'FRE': 'Free Zones',
    'FRO': 'Faeroe Islands',
    'FSM': 'Micronesia, Fed. Sts.',
    'GAB': 'Gabon',
    'GAZ': 'Gaza Strip',
    'GBR': 'United Kingdom',
    'GEO': 'Georgia',
    'GHA': 'Ghana',
    'GIB': 'Gibraltar',
    'GIN': 'Guinea',
    'GLP': 'Guadeloupe',
    'GMB': 'Gambia, The',
    'GNB': 'Guinea-Bissau',
    'GNQ': 'Equatorial Guinea',
    'GRC': 'Greece',
    'GRD': 'Grenada',
    'GRL': 'Greenland',
    'GTM': 'Guatemala',
    'GUF': 'French Guiana',
    'GUM': 'Guam',
    'GUY': 'Guyana',
    'HKG': 'Hong Kong, China',
    'HMD': 'Heard Island and McDonald Isla',
    'HND': 'Honduras',
    'HRV': 'Croatia',
    'HTI': 'Haiti',
    'HUN': 'Hungary',
    'IDN': 'Indonesia',
    'IND': 'India',
    'IOT': 'British Indian Ocean Ter.',
    'IRL': 'Ireland',
    'IRN': 'Iran, Islamic Rep.',
    'IRQ': 'Iraq',
    'ISL': 'Iceland',
    'ISR': 'Israel',
    'ITA': 'Italy',
    'JAM': 'Jamaica',
    'JOR': 'Jordan',
    'JPN': 'Japan',
    'JTN': 'Jhonston Island',
    'KAZ': 'Kazakhstan',
    'KEN': 'Kenya',
    'KGZ': 'Kyrgyz Republic',
    'KHM': 'Cambodia',
    'KIR': 'Kiribati',
    'KN1': 'Saint Kitts-Nevis-Anguilla-Aru',
    'KNA': 'St. Kitts and Nevis',
    'KOR': 'Korea, Rep.',
    'KSV': 'Kosovo',
    'KWT': 'Kuwait',
    'LAO': 'Lao PDR',
    'LBN': 'Lebanon',
    'LBR': 'Liberia',
    'LBY': 'Libya',
    'LCA': 'St. Lucia',
    'LIE': 'Liechtenstein',
    'LKA': 'Sri Lanka',
    'LSO': 'Lesotho',
    'LTU': 'Lithuania',
    'LUX': 'Luxembourg',
    'LVA': 'Latvia',
    'MAC': 'Macao',
    'MAF': 'Saint Martin (French Part)',
    'MAR': 'Morocco',
    'MCO': 'Monaco',
    'MDA': 'Moldova',
    'MDG': 'Madagascar',
    'MDV': 'Maldives',
    'MEX': 'Mexico',
    'MHL': 'Marshall Islands',
    'MID': 'Midway Islands',
    'MKD': 'North Macedonia',
    'MLI': 'Mali',
    'MLT': 'Malta',
    'MMR': 'Myanmar',
    'MNG': 'Mongolia',
    'MNP': 'Northern Mariana Islands',
    'MNT': 'Montenegro',
    'MOZ': 'Mozambique',
    'MRT': 'Mauritania',
    'MSR': 'Montserrat',
    'MTQ': 'Martinique',
    'MUS': 'Mauritius',
    'MWI': 'Malawi',
    'MYS': 'Malaysia',
    'MYT': 'Mayotte',
    'NAM': 'Namibia',
    'NCL': 'New Caledonia',
    'NER': 'Niger',
    'NFK': 'Norfolk Island',
    'NGA': 'Nigeria',
    'NIC': 'Nicaragua',
    'NIU': 'Niue',
    'NLD': 'Netherlands',
    'NOR': 'Norway',
    'NPL': 'Nepal',
    'NRU': 'Nauru',
    'NZE': 'Neutral Zone',
    'NZL': 'New Zealand',
    'OAS': 'Other Asia, nes',
    'OMN': 'Oman',
    'PAK': 'Pakistan',
    'PAN': 'Panama',
    'PCE': 'Pacific Islands',
    'PCN': 'Pitcairn',
    'PCZ': 'Fm Panama Cz',
    'PER': 'Peru',
    'PHL': 'Philippines',
    'PLW': 'Palau',
    'PMY': 'Pen Malaysia',
    'PNG': 'Papua New Guinea',
    'POL': 'Poland',
    'PRI': 'Puerto Rico',
    'PRK': 'Korea, Dem. Rep.',
    'PRT': 'Portugal',
    'PRY': 'Paraguay',
    'PSE': 'Occ.Pal.Terr',
    'PYF': 'French Polynesia',
    'QAT': 'Qatar',
    'REU': 'Reunion',
    'ROM': 'Romania',
    'RUS': 'Russian Federation',
    'RWA': 'Rwanda',
    'RYU': 'Ryukyu Is',
    'SAU': 'Saudi Arabia',
    'SBH': 'Sabah',
    'SDN': 'Fm Sudan',
    'SEN': 'Senegal',
    'SER': 'Serbia, FR(Serbia/Montenegro)',
    'SGP': 'Singapore',
    'SGS': 'South Georgia and the South Sa',
    'SHN': 'Saint Helena',
    'SIK': 'SIKKIM',
    'SJM': 'Svalbard and Jan Mayen Is',
    'SLB': 'Solomon Islands',
    'SLE': 'Sierra Leone',
    'SLV': 'El Salvador',
    'SMR': 'San Marino',
    'SOM': 'Somalia',
    'SPE': 'Special Categories',
    'SPM': 'Saint Pierre and Miquelon',
    'SSD': 'South Sudan',
    'STP': 'Sao Tome and Principe',
    'SUD': 'Sudan',
    'SUR': 'Suriname',
    'SVK': 'Slovak Republic',
    'SVN': 'Slovenia',
    'SVR': 'Fm Vietnam Rp',
    'SVU': 'Soviet Union',
    'SWE': 'Sweden',
    'SWK': 'Sarawak',
    'SWZ': 'Eswatini',
    'SXM': 'Saint Maarten (Dutch part)',
    'SYC': 'Seychelles',
    'SYR': 'Syrian Arab Republic',
    'TAN': 'Fm Tanganyik',
    'TCA': 'Turks and Caicos Isl.',
    'TCD': 'Chad',
    'TGO': 'Togo',
    'THA': 'Thailand',
    'TJK': 'Tajikistan',
    'TKL': 'Tokelau',
    'TKM': 'Turkmenistan',
    'TMP': 'East Timor',
    'TON': 'Tonga',
    'TTO': 'Trinidad and Tobago',
    'TUN': 'Tunisia',
    'TUR': 'Turkey',
    'TUV': 'Tuvalu',
    'TWN': 'Taiwan, China',
    'TZA': 'Tanzania',
    'UGA': 'Uganda',
    'UKR': 'Ukraine',
    'UMI': 'United States Minor Outlying I',
    'UNS': 'Unspecified',
    'URY': 'Uruguay',
    'USA': 'United States',
    'USP': 'Us Msc.Pac.I',
    'UZB': 'Uzbekistan',
    'VAT': 'Holy See',
    'VCT': 'St. Vincent and the Grenadines',
    'VDR': 'Fm Vietnam DR',
    'VEN': 'Venezuela',
    'VGB': 'British Virgin Islands',
    'VIR': 'Virgin Islands (U.S.)',
    'VNM': 'Vietnam',
    'VUT': 'Vanuatu',
    'WAK': 'Wake Island',
    'WLF': 'Wallis and Futura Isl.',
    'WSM': 'Samoa',
    'YDR': 'Yemen Democratic',
    'YEM': 'Yemen',
    'YUG': 'Yugoslavia,FR(Serbia/Montenegr',
    'ZAF': 'South Africa',
    'ZAR': 'Congo, Dem. Rep.',
    'ZMB': 'Zambia',
    'ZPM': 'Fm Zanz-Pemb',
    'ZW1': 'Fm Rhod Nyas',
    'ZWE': 'Zimbabwe'
}